name: laravel-ecommerce
services:
- name: app
  github:
    repo: your-github-username/your-repo-name
    branch: main
  build_command: |
    composer install --no-dev --optimize-autoloader
    npm install
    npm run build
    chmod -R 777 storage bootstrap
    chmod -R 775 app/Providers lang routes
    php artisan migrate
    php artisan storage:link
    php artisan config:clear
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
  dockerfile_path: Dockerfile
  http_port: 9000
  source_dir: ./
  envs:
  - key: APP_NAME
    value: sour-shop
    scope: RUN_AND_BUILD_TIME
  - key: APP_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: APP_DEBUG
    value: "false"
    scope: RUN_AND_BUILD_TIME
  - key: APP_KEY
    value: ${APP_KEY}
    scope: RUN_AND_BUILD_TIME
  - key: APP_URL
    value: https://${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
  - key: DB_HOST
    value: ${db.HOSTNAME}
    scope: RUN_AND_BUILD_TIME
  - key: DB_PORT
    value: "25060"
    scope: RUN_AND_BUILD_TIME
  - key: DB_DATABASE
    value: ${db.DATABASE}
    scope: RUN_AND_BUILD_TIME
  - key: DB_USERNAME
    value: ${db.USERNAME}
    scope: RUN_AND_BUILD_TIME
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
    scope: RUN_AND_BUILD_TIME
  - key: CACHE_DRIVER
    value: redis
    scope: RUN_AND_BUILD_TIME
  - key: QUEUE_CONNECTION
    value: redis
    scope: RUN_AND_BUILD_TIME
  - key: SESSION_DRIVER
    value: redis
    scope: RUN_AND_BUILD_TIME
  - key: REDIS_HOST
    value: ${redis.HOSTNAME}
    scope: RUN_AND_BUILD_TIME
  - key: REDIS_PORT
    value: "25061"
    scope: RUN_AND_BUILD_TIME
  - key: REDIS_PASSWORD
    value: ${redis.PASSWORD}
    scope: RUN_AND_BUILD_TIME
  http_routes:
  - path: /
    preserve_path_prefix: true
  health_check:
    http_path: /health
  run_command: php artisan octane:start --host=0.0.0.0 --port=9000
  
- name: web
  image:
    registry_type: DOCR
    repository: nginx
    tag: latest
  http_port: 80
  source_dir: ./
  envs:
  - key: NGINX_HOST
    value: "0.0.0.0"
    scope: RUN_TIME
  - key: NGINX_PORT
    value: "80"
    scope: RUN_TIME

databases:
- engine: MYSQL
  name: db
  version: "8.0"

- engine: REDIS
  name: redis
  version: "7"

static_sites:
- name: assets
  source_dir: public/build
  routes:
  - path: /build
    preserve_path_prefix: true

domains:
- name: your-domain.com
  type: PRIMARY
